"""
Intelligence database layer — stores and retrieves all AI-grade memory tables.

Tables added:
  - context_memory      : short-term conversation context (rolling window)
  - long_term_profile   : persistent user preferences / facts
  - relationship_memory : people → role/priority mappings
  - alias_map           : user-defined phrase → canonical app/action mappings
  - behavior_patterns   : timestamped action log for routine detection
  - preference_scores   : ranked choices per intent category with confidence
  - assistant_reflections: daily/weekly summaries generated by reflection engine
"""

import sqlite3
import json
import logging
import threading
from datetime import datetime
from pathlib import Path
from typing import Optional, List, Dict, Any

logger = logging.getLogger("JARVIS.IntelDB")

_ROOT = Path(__file__).resolve().parent.parent
INTEL_DB_PATH = _ROOT / "data" / "jarvis_intelligence.db"


class IntelligenceDB:
    def __init__(self):
        INTEL_DB_PATH.parent.mkdir(parents=True, exist_ok=True)
        self._lock = threading.Lock()
        self.conn = sqlite3.connect(
            str(INTEL_DB_PATH),
            check_same_thread=False,
            detect_types=sqlite3.PARSE_DECLTYPES,
        )
        self.conn.row_factory = sqlite3.Row
        self.conn.execute("PRAGMA journal_mode=WAL")
        self._init_schema()

    def _init_schema(self):
        with self._lock:
            self.conn.execute("BEGIN")
            try:
                # Short-term conversation context
                self.conn.execute("""
                    CREATE TABLE IF NOT EXISTS context_memory (
                        id         INTEGER PRIMARY KEY AUTOINCREMENT,
                        session_id TEXT    NOT NULL,
                        role       TEXT    NOT NULL CHECK(role IN ('user','assistant')),
                        text       TEXT    NOT NULL,
                        intent     TEXT,
                        entities   TEXT    DEFAULT '{}',
                        ts         TEXT    DEFAULT (datetime('now'))
                    )
                """)
                # Long-term user profile facts
                self.conn.execute("""
                    CREATE TABLE IF NOT EXISTS long_term_profile (
                        id         INTEGER PRIMARY KEY AUTOINCREMENT,
                        category   TEXT    NOT NULL,
                        key        TEXT    NOT NULL,
                        value      TEXT    NOT NULL,
                        confidence REAL    DEFAULT 1.0,
                        source     TEXT    DEFAULT 'explicit',
                        updated    TEXT    DEFAULT (datetime('now')),
                        UNIQUE(category, key)
                    )
                """)
                # People / relationship memory
                self.conn.execute("""
                    CREATE TABLE IF NOT EXISTS relationship_memory (
                        id       INTEGER PRIMARY KEY AUTOINCREMENT,
                        name     TEXT    NOT NULL UNIQUE,
                        role     TEXT,
                        notes    TEXT    DEFAULT '[]',
                        priority INTEGER DEFAULT 0,
                        updated  TEXT    DEFAULT (datetime('now'))
                    )
                """)
                # User-defined aliases (editor = VS Code, etc.)
                self.conn.execute("""
                    CREATE TABLE IF NOT EXISTS alias_map (
                        id         INTEGER PRIMARY KEY AUTOINCREMENT,
                        alias      TEXT    NOT NULL UNIQUE,
                        canonical  TEXT    NOT NULL,
                        category   TEXT    DEFAULT 'app',
                        confidence REAL    DEFAULT 1.0,
                        use_count  INTEGER DEFAULT 0,
                        created    TEXT    DEFAULT (datetime('now')),
                        updated    TEXT    DEFAULT (datetime('now'))
                    )
                """)
                # Raw timestamped behavior log for pattern analysis
                self.conn.execute("""
                    CREATE TABLE IF NOT EXISTS behavior_patterns (
                        id         INTEGER PRIMARY KEY AUTOINCREMENT,
                        action     TEXT    NOT NULL,
                        target     TEXT,
                        hour       INTEGER,
                        weekday    INTEGER,
                        mode       TEXT,
                        ts         TEXT    DEFAULT (datetime('now'))
                    )
                """)
                # Learned preference scores per category
                self.conn.execute("""
                    CREATE TABLE IF NOT EXISTS preference_scores (
                        id         INTEGER PRIMARY KEY AUTOINCREMENT,
                        category   TEXT    NOT NULL,
                        choice     TEXT    NOT NULL,
                        score      REAL    DEFAULT 0.5,
                        count      INTEGER DEFAULT 1,
                        last_used  TEXT    DEFAULT (datetime('now')),
                        UNIQUE(category, choice)
                    )
                """)
                # Daily/weekly reflection summaries
                self.conn.execute("""
                    CREATE TABLE IF NOT EXISTS assistant_reflections (
                        id        INTEGER PRIMARY KEY AUTOINCREMENT,
                        period    TEXT    NOT NULL,
                        summary   TEXT    NOT NULL,
                        insights  TEXT    DEFAULT '[]',
                        ts        TEXT    DEFAULT (datetime('now'))
                    )
                """)
                self.conn.commit()
            except Exception as exc:
                self.conn.rollback()
                logger.error(f"IntelligenceDB schema init failed: {exc}")
                raise

    # ── Context Memory (short-term) ──────────────────────────────────────────

    def add_context(self, session_id: str, role: str, text: str,
                    intent: str = None, entities: dict = None):
        with self._lock:
            try:
                self.conn.execute(
                    """INSERT INTO context_memory (session_id, role, text, intent, entities)
                       VALUES (?,?,?,?,?)""",
                    (session_id, role, text, intent, json.dumps(entities or {}))
                )
                self.conn.commit()
            except sqlite3.Error as exc:
                logger.error(f"add_context error: {exc}")

    def get_context(self, session_id: str, limit: int = 10) -> List[Dict]:
        with self._lock:
            try:
                rows = self.conn.execute(
                    """SELECT role, text, intent, entities, ts FROM context_memory
                       WHERE session_id = ? ORDER BY ts DESC LIMIT ?""",
                    (session_id, limit)
                ).fetchall()
                result = [dict(r) for r in reversed(rows)]
                for r in result:
                    try:
                        r["entities"] = json.loads(r["entities"])
                    except Exception:
                        r["entities"] = {}
                return result
            except sqlite3.Error as exc:
                logger.error(f"get_context error: {exc}")
                return []

    def get_recent_context_texts(self, days: int = 7, limit: int = 200) -> List[str]:
        with self._lock:
            try:
                rows = self.conn.execute(
                    """SELECT text FROM context_memory
                       WHERE ts >= datetime('now', ?)
                       ORDER BY ts DESC LIMIT ?""",
                    (f"-{days} days", limit),
                ).fetchall()
                return [r["text"] for r in rows if r["text"]]
            except sqlite3.Error as exc:
                logger.error(f"get_recent_context_texts error: {exc}")
                return []

    def clear_old_context(self, session_id: str, keep: int = 20):
        """Keep only the N most recent context entries for a session."""
        with self._lock:
            try:
                self.conn.execute(
                    """DELETE FROM context_memory WHERE session_id = ?
                       AND id NOT IN (
                           SELECT id FROM context_memory WHERE session_id = ?
                           ORDER BY ts DESC LIMIT ?
                       )""",
                    (session_id, session_id, keep)
                )
                self.conn.commit()
            except sqlite3.Error as exc:
                logger.error(f"clear_old_context error: {exc}")

    # ── Long-term Profile ─────────────────────────────────────────────────────

    def set_profile(self, category: str, key: str, value: str,
                    confidence: float = 1.0, source: str = "explicit"):
        with self._lock:
            try:
                self.conn.execute(
                    """INSERT INTO long_term_profile (category, key, value, confidence, source)
                       VALUES (?,?,?,?,?)
                       ON CONFLICT(category, key) DO UPDATE SET
                         value = excluded.value,
                         confidence = excluded.confidence,
                         source = excluded.source,
                         updated = datetime('now')""",
                    (category, key, value, confidence, source)
                )
                self.conn.commit()
            except sqlite3.Error as exc:
                logger.error(f"set_profile error: {exc}")

    def get_profile(self, category: str = None) -> List[Dict]:
        with self._lock:
            try:
                if category:
                    rows = self.conn.execute(
                        "SELECT * FROM long_term_profile WHERE category = ? ORDER BY key",
                        (category,)
                    ).fetchall()
                else:
                    rows = self.conn.execute(
                        "SELECT * FROM long_term_profile ORDER BY category, key"
                    ).fetchall()
                return [dict(r) for r in rows]
            except sqlite3.Error as exc:
                logger.error(f"get_profile error: {exc}")
                return []

    def get_profile_value(self, category: str, key: str) -> Optional[str]:
        with self._lock:
            try:
                row = self.conn.execute(
                    "SELECT value FROM long_term_profile WHERE category=? AND key=?",
                    (category, key)
                ).fetchone()
                return row[0] if row else None
            except sqlite3.Error as exc:
                logger.error(f"get_profile_value error: {exc}")
                return None

    # ── Relationship Memory ───────────────────────────────────────────────────

    def upsert_relationship(self, name: str, role: str = None,
                            note: str = None, priority: int = 0):
        with self._lock:
            try:
                existing = self.conn.execute(
                    "SELECT notes FROM relationship_memory WHERE name=?",
                    (name.lower(),)
                ).fetchone()
                notes = []
                if existing:
                    try:
                        notes = json.loads(existing[0])
                    except Exception:
                        notes = []
                if note and note not in notes:
                    notes.append(note)
                self.conn.execute(
                    """INSERT INTO relationship_memory (name, role, notes, priority)
                       VALUES (?,?,?,?)
                       ON CONFLICT(name) DO UPDATE SET
                         role = COALESCE(excluded.role, role),
                         notes = excluded.notes,
                         priority = excluded.priority,
                         updated = datetime('now')""",
                    (name.lower(), role, json.dumps(notes), priority)
                )
                self.conn.commit()
            except sqlite3.Error as exc:
                logger.error(f"upsert_relationship error: {exc}")

    def get_relationship(self, name: str) -> Optional[Dict]:
        with self._lock:
            try:
                row = self.conn.execute(
                    "SELECT * FROM relationship_memory WHERE name=?",
                    (name.lower(),)
                ).fetchone()
                if row:
                    d = dict(row)
                    try:
                        d["notes"] = json.loads(d["notes"])
                    except Exception:
                        d["notes"] = []
                    return d
                return None
            except sqlite3.Error as exc:
                logger.error(f"get_relationship error: {exc}")
                return None

    def get_all_relationships(self) -> List[Dict]:
        with self._lock:
            try:
                rows = self.conn.execute(
                    "SELECT * FROM relationship_memory ORDER BY priority DESC, name"
                ).fetchall()
                result = []
                for r in rows:
                    d = dict(r)
                    try:
                        d["notes"] = json.loads(d["notes"])
                    except Exception:
                        d["notes"] = []
                    result.append(d)
                return result
            except sqlite3.Error as exc:
                logger.error(f"get_all_relationships error: {exc}")
                return []

    # ── Alias Map ─────────────────────────────────────────────────────────────

    def set_alias(self, alias: str, canonical: str,
                  category: str = "app", confidence: float = 1.0):
        with self._lock:
            try:
                self.conn.execute(
                    """INSERT INTO alias_map (alias, canonical, category, confidence)
                       VALUES (?,?,?,?)
                       ON CONFLICT(alias) DO UPDATE SET
                         canonical = excluded.canonical,
                         category = excluded.category,
                         confidence = excluded.confidence,
                         updated = datetime('now')""",
                    (alias.lower().strip(), canonical, category, confidence)
                )
                self.conn.commit()
                logger.info(f"Alias learned: '{alias}' → '{canonical}'")
            except sqlite3.Error as exc:
                logger.error(f"set_alias error: {exc}")

    def resolve_alias(self, alias: str) -> Optional[str]:
        with self._lock:
            try:
                row = self.conn.execute(
                    "SELECT canonical FROM alias_map WHERE alias=?",
                    (alias.lower().strip(),)
                ).fetchone()
                if row:
                    self.conn.execute(
                        "UPDATE alias_map SET use_count = use_count + 1 WHERE alias=?",
                        (alias.lower().strip(),)
                    )
                    self.conn.commit()
                    return row[0]
                return None
            except sqlite3.Error as exc:
                logger.error(f"resolve_alias error: {exc}")
                return None

    def get_all_aliases(self) -> List[Dict]:
        with self._lock:
            try:
                return [dict(r) for r in self.conn.execute(
                    "SELECT * FROM alias_map ORDER BY use_count DESC"
                ).fetchall()]
            except sqlite3.Error as exc:
                logger.error(f"get_all_aliases error: {exc}")
                return []

    # ── Behavior Patterns ─────────────────────────────────────────────────────

    def log_behavior(self, action: str, target: str = None, mode: str = None):
        now = datetime.now()
        with self._lock:
            try:
                self.conn.execute(
                    """INSERT INTO behavior_patterns (action, target, hour, weekday, mode)
                       VALUES (?,?,?,?,?)""",
                    (action, target, now.hour, now.weekday(), mode)
                )
                self.conn.commit()
            except sqlite3.Error as exc:
                logger.error(f"log_behavior error: {exc}")

    def get_behavior_frequency(self, action: str = None, target: str = None,
                               days: int = 30) -> List[Dict]:
        """Return frequency counts for action/target combos."""
        with self._lock:
            try:
                conditions = ["ts >= datetime('now', ?)"]
                params: list = [f"-{days} days"]
                if action:
                    conditions.append("action = ?")
                    params.append(action)
                if target:
                    conditions.append("target = ?")
                    params.append(target)
                where = " AND ".join(conditions)
                rows = self.conn.execute(
                    f"""SELECT action, target, hour, weekday, COUNT(*) as freq
                        FROM behavior_patterns WHERE {where}
                        GROUP BY action, target, hour, weekday
                        ORDER BY freq DESC""",
                    params
                ).fetchall()
                return [dict(r) for r in rows]
            except sqlite3.Error as exc:
                logger.error(f"get_behavior_frequency error: {exc}")
                return []

    def get_top_behaviors(self, days: int = 7, limit: int = 20) -> List[Dict]:
        with self._lock:
            try:
                rows = self.conn.execute(
                    """SELECT action, target, COUNT(*) as freq
                       FROM behavior_patterns
                       WHERE ts >= datetime('now', ?)
                       GROUP BY action, target
                       ORDER BY freq DESC LIMIT ?""",
                    (f"-{days} days", limit)
                ).fetchall()
                return [dict(r) for r in rows]
            except sqlite3.Error as exc:
                logger.error(f"get_top_behaviors error: {exc}")
                return []

    # ── Preference Scores ─────────────────────────────────────────────────────

    def update_preference(self, category: str, choice: str, delta: float = 0.1):
        """Increment preference score for a choice within a category."""
        with self._lock:
            try:
                self.conn.execute(
                    """INSERT INTO preference_scores (category, choice, score, count)
                       VALUES (?,?,?,1)
                       ON CONFLICT(category, choice) DO UPDATE SET
                         score = MIN(1.0, score + ?),
                         count = count + 1,
                         last_used = datetime('now')""",
                    (category, choice, 0.5 + delta, delta)
                )
                self.conn.commit()
            except sqlite3.Error as exc:
                logger.error(f"update_preference error: {exc}")

    def get_top_preference(self, category: str) -> Optional[Dict]:
        with self._lock:
            try:
                row = self.conn.execute(
                    """SELECT choice, score, count FROM preference_scores
                       WHERE category=? ORDER BY score DESC LIMIT 1""",
                    (category,)
                ).fetchone()
                return dict(row) if row else None
            except sqlite3.Error as exc:
                logger.error(f"get_top_preference error: {exc}")
                return None

    def get_preferences(self, category: str) -> List[Dict]:
        with self._lock:
            try:
                rows = self.conn.execute(
                    """SELECT choice, score, count, last_used FROM preference_scores
                       WHERE category=? ORDER BY score DESC""",
                    (category,)
                ).fetchall()
                return [dict(r) for r in rows]
            except sqlite3.Error as exc:
                logger.error(f"get_preferences error: {exc}")
                return []

    # ── Reflections ───────────────────────────────────────────────────────────

    def save_reflection(self, period: str, summary: str, insights: list):
        with self._lock:
            try:
                self.conn.execute(
                    """INSERT INTO assistant_reflections (period, summary, insights)
                       VALUES (?,?,?)""",
                    (period, summary, json.dumps(insights))
                )
                self.conn.commit()
            except sqlite3.Error as exc:
                logger.error(f"save_reflection error: {exc}")

    def get_latest_reflection(self) -> Optional[Dict]:
        with self._lock:
            try:
                row = self.conn.execute(
                    "SELECT * FROM assistant_reflections ORDER BY ts DESC LIMIT 1"
                ).fetchone()
                if row:
                    d = dict(row)
                    try:
                        d["insights"] = json.loads(d["insights"])
                    except Exception:
                        d["insights"] = []
                    return d
                return None
            except sqlite3.Error as exc:
                logger.error(f"get_latest_reflection error: {exc}")
                return None

    def close(self):
        with self._lock:
            try:
                self.conn.close()
            except Exception as exc:
                logger.error(f"IntelligenceDB close error: {exc}")
